string[] joint_names   # Names of the joints we're waiting to settle
float64[] tolerances   # Tolerance on each of the specified joints
duration max_step      # The maximum timestep between two elements in an interval
uint32 cache_size      # The size of our cache when searching for an interval
---
---
